# Generated by Django 3.0.6 on 2020-09-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('chara', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('gold', models.BigIntegerField(default=0)),
                ('items', models.ManyToManyField(to='item.Item')),
                ('king', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='king_of', to='chara.Chara')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountryOfficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=20)),
                ('chara', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official', to='chara.Chara')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='country.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
