# Generated by Django 3.0.6 on 2021-01-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0002_auto_20200901_1442'),
        ('country', '0003_countryjoinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryjoinrequest',
            name='chara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_join_requests', to='chara.Chara'),
        ),
    ]
