# Generated by Django 3.0.6 on 2021-06-29 17:40

from django.db import migrations, models
import django.db.models.deletion


def create_country_setting(apps, schema_editor):
    Country = apps.get_model('country', 'Country')
    CountrySetting = apps.get_model('country', 'CountrySetting')
    for country in Country.objects.all():
        CountrySetting.objects.create(country=country)


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_country_item_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('introduction', models.TextField(blank=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='setting', to='country.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_country_setting)
    ]
