# Generated by Django 3.0.6 on 2021-03-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0004_chararecord_level_down_count'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorldChatMessage',
            new_name='PublicChatMessage',
        ),
    ]
