# Generated by Django 3.0.6 on 2021-03-08 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_country_item_limit'),
        ('system', '0003_auto_20210308_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrychatmessage',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='country.Country'),
        ),
    ]
