# Generated by Django 3.0.6 on 2021-07-11 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0011_chara_avatar_version'),
        ('system', '0006_privatechatmessage_is_system_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.CharField(max_length=400)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chara.Chara')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
