# Generated by Django 3.0.6 on 2021-07-11 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_teamchatmessage'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchatmessage',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.Team'),
        ),
    ]
