# Generated by Django 3.2 on 2021-07-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_teamchatmessage_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='content',
            field=models.TextField(),
        ),
    ]
