# Generated by Django 3.2 on 2022-01-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_log_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('note', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
