# Generated by Django 4.0 on 2022-03-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('system', '0010_changelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sender_name', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=400)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
