# Generated by Django 3.0.6 on 2020-09-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ability', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('use_effect_param', models.IntegerField(null=True)),
                ('is_consumable', models.BooleanField(default=False)),
                ('value', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('ability_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ability_1_itemtypes', to='ability.Ability')),
                ('ability_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ability_2_itemtypes', to='ability.Ability')),
                ('attribute_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='world.AttributeType')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.ItemCategory')),
                ('element_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='world.ElementType')),
                ('slot_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='world.SlotType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemTypePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemTypePoolGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemUseEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemTypePoolMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.PositiveIntegerField(default=1)),
                ('weight', models.PositiveIntegerField(default=10000)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.ItemType')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='item.ItemTypePool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemTypePoolGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('weight', models.PositiveIntegerField(default=10000)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='item.ItemTypePoolGroup')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.ItemTypePool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='itemtype',
            name='use_effect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='item.ItemUseEffect'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.ItemType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.Item')),
                ('quality', models.CharField(choices=[('稀有', '稀有'), ('優良', '優良'), ('普通', '普通')], max_length=2)),
                ('custom_name', models.CharField(max_length=20)),
                ('attack_add_on', models.IntegerField(default=0)),
                ('defense_add_on', models.IntegerField(default=0)),
                ('weight_add_on', models.IntegerField(default=0)),
                ('upgrade_times', models.IntegerField(default=0)),
                ('ability_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ability_1_items', to='ability.Ability')),
                ('ability_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ability_2_items', to='ability.Ability')),
                ('element_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='world.ElementType')),
            ],
            options={
                'abstract': False,
            },
            bases=('item.item',),
        ),
    ]
