# Generated by Django 3.0.6 on 2021-01-31 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('evolution_proficiency_cost', models.IntegerField()),
                ('attack_growth', models.IntegerField()),
                ('defense_growth', models.IntegerField()),
                ('weight_growth', models.IntegerField()),
                ('item_type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pet_type', to='item.ItemType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PetTypeEvolutionTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('weight', models.IntegerField()),
                ('pet_type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evolution_targets', to='item.PetType')),
                ('target_pet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.PetType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
