# Generated by Django 3.0.6 on 2021-01-31 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_pettype_pettypeevolutiontarget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pettype',
            old_name='evolution_proficiency_cost',
            new_name='upgrade_proficiency_cost',
        ),
    ]
