# Generated by Django 3.0.6 on 2021-01-31 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210131_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettypeevolutiontarget',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolution_targets', to='item.PetType'),
        ),
    ]
