# Generated by Django 3.2 on 2021-11-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_equipment_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='attack_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='defense_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weight_base',
            field=models.IntegerField(default=0),
        ),
    ]
