# Generated by Django 4.0 on 2022-04-22 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0016_battleeffecttype_battleeffect'),
        ('item', '0007_auto_20211114_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='battle_effect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='battle.battleeffect'),
        ),
    ]
