# Generated by Django 3.0.6 on 2020-09-01 14:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('job', '0001_initial'),
        ('world', '0001_initial'),
        ('ability', '0002_auto_20200901_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleMapTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('next_action_time', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('proficiency', models.BigIntegerField(default=0)),
                ('gold', models.BigIntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('hp_max', models.PositiveIntegerField()),
                ('hp', models.PositiveIntegerField()),
                ('mp_max', models.PositiveIntegerField()),
                ('mp', models.PositiveIntegerField()),
                ('abilities', models.ManyToManyField(to='ability.Ability')),
                ('bag_items', models.ManyToManyField(related_name='bag_item_chara', to='item.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharaBuffType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_positive', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharaSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='chara.Chara')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Item', unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.SlotType')),
            ],
        ),
        migrations.CreateModel(
            name='CharaSkillSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('hp_percentage', models.PositiveSmallIntegerField()),
                ('mp_percentage', models.PositiveSmallIntegerField()),
                ('order', models.IntegerField()),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_settings', to='chara.Chara')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharaRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_battle', models.IntegerField(default=0)),
                ('monthly_level_up', models.IntegerField(default=0)),
                ('chara', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='chara.Chara')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharaIntroduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('chara', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='introduction', to='chara.Chara')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharaBuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.IntegerField(null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chara.Chara')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chara.CharaBuffType')),
            ],
        ),
        migrations.CreateModel(
            name='CharaAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('proficiency', models.IntegerField(default=0)),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='chara.Chara')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='world.AttributeType')),
            ],
        ),
    ]
