# Generated by Django 3.0.6 on 2020-09-01 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('battle', '0002_auto_20200901_1442'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ability', '0002_auto_20200901_1442'),
        ('country', '0001_initial'),
        ('job', '0001_initial'),
        ('world', '0001_initial'),
        ('chara', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chara',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizens', to='country.Country'),
        ),
        migrations.AddField(
            model_name='chara',
            name='element_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='world.ElementType'),
        ),
        migrations.AddField(
            model_name='chara',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.Job'),
        ),
        migrations.AddField(
            model_name='chara',
            name='job_ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_ability_charas', to='ability.Ability'),
        ),
        migrations.AddField(
            model_name='chara',
            name='live_ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='live_ability_charas', to='ability.Ability'),
        ),
        migrations.AddField(
            model_name='chara',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='world.Location'),
        ),
        migrations.AddField(
            model_name='chara',
            name='main_ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_ability_charas', to='ability.Ability'),
        ),
        migrations.AddField(
            model_name='chara',
            name='storage_items',
            field=models.ManyToManyField(related_name='storage_item_chara', to='item.Item'),
        ),
        migrations.AddField(
            model_name='chara',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battlemapticket',
            name='battle_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleMap'),
        ),
        migrations.AddField(
            model_name='battlemapticket',
            name='chara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_map_tickets', to='chara.Chara'),
        ),
        migrations.AlterUniqueTogether(
            name='charaslot',
            unique_together={('chara', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='charabuff',
            unique_together={('chara', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='charaattribute',
            unique_together={('chara', 'type')},
        ),
    ]
