# Generated by Django 3.0.6 on 2021-02-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0002_auto_20200901_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='chara',
            name='bag_item_limit',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='chara',
            name='storage_item_limit',
            field=models.IntegerField(default=15),
        ),
    ]
