# Generated by Django 3.0.6 on 2021-02-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0003_auto_20210204_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='chararecord',
            name='level_down_count',
            field=models.IntegerField(default=0),
        ),
    ]
