# Generated by Django 3.0.6 on 2021-05-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0004_chararecord_level_down_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chara',
            name='pvp_points',
            field=models.IntegerField(default=1000),
        ),
    ]
