# Generated by Django 3.0.6 on 2021-05-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0005_chara_pvp_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='chararecord',
            name='country_monster_quest_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chararecord',
            name='today_battle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chararecord',
            name='world_monster_quest_counter',
            field=models.IntegerField(default=0),
        ),
    ]
