# Generated by Django 3.0.6 on 2021-06-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0006_auto_20210527_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chararecord',
            name='monthly_level_up',
        ),
    ]
