# Generated by Django 3.0.6 on 2021-06-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0008_auto_20210616_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='chara',
            name='member_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
