# Generated by Django 3.0.6 on 2021-06-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0009_chara_member_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chara',
            old_name='member_points',
            new_name='member_point',
        ),
    ]
