# Generated by Django 3.0.6 on 2021-07-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0010_auto_20210616_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='chara',
            name='avatar_version',
            field=models.IntegerField(default=0),
        ),
    ]
