# Generated by Django 3.2 on 2021-08-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0012_chara_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='chara',
            name='has_transfer_permission',
            field=models.BooleanField(default=True),
        ),
    ]
