# Generated by Django 3.2 on 2021-11-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0014_auto_20210922_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='chara',
            name='luck_base',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
