# Generated by Django 3.2 on 2021-12-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0015_chara_luck_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharaBuffEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='charabuff',
            old_name='due_date',
            new_name='due_time',
        ),
        migrations.RemoveField(
            model_name='charabuff',
            name='value',
        ),
        migrations.RemoveField(
            model_name='charabufftype',
            name='is_positive',
        ),
        migrations.AlterField(
            model_name='charabuff',
            name='chara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffs', to='chara.chara'),
        ),
        migrations.AlterField(
            model_name='charabufftype',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='charabufftype',
            name='effect',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chara.charabuffeffect'),
            preserve_default=False,
        ),
    ]
