# Generated by Django 3.2 on 2021-12-12 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20211114_1205'),
        ('chara', '0018_charabufftype_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharaFarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('due_time', models.DateTimeField(null=True)),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='chara.chara')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
