# Generated by Django 3.2 on 2022-01-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0013_arena'),
        ('chara', '0020_alter_charaslot_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharaPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('due_time', models.DateTimeField()),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='chara.chara')),
                ('target_chara', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chara.chara')),
                ('target_monster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.monster')),
            ],
            options={
                'unique_together': {('chara', 'target_chara'), ('chara', 'target_monster')},
            },
        ),
        migrations.AddField(
            model_name='chara',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_partner_of', to='chara.charapartner'),
        ),
    ]
