# Generated by Django 4.0 on 2022-02-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0022_alter_charapartner_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharaAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='chara.chara')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chara.charaachievement')),
            ],
            options={
                'unique_together': {('chara', 'type')},
            },
        ),
        migrations.CreateModel(
            name='CharaAchievementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharaAchievementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('requirement', models.IntegerField()),
                ('name', models.CharField(max_length=20, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chara.charaachievement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharaAchievementCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chara.charaachievement')),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_counters', to='chara.chara')),
            ],
            options={
                'unique_together': {('chara', 'category')},
            },
        ),
    ]
