# Generated by Django 4.0 on 2022-02-07 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0023_charaachievement_charaachievementcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charaachievement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chara.charaachievementtype'),
        ),
        migrations.AlterField(
            model_name='charaachievementcounter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chara.charaachievementcategory'),
        ),
        migrations.AlterField(
            model_name='charaachievementtype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chara.charaachievementcategory'),
        ),
    ]
