# Generated by Django 4.0 on 2022-02-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0024_alter_charaachievement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charaachievementtype',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
