# Generated by Django 4.0 on 2022-02-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0025_alter_charaachievementtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charaachievementcounter',
            name='value',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charaachievementtype',
            name='requirement',
            field=models.BigIntegerField(),
        ),
    ]
