# Generated by Django 4.0 on 2022-02-09 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0026_alter_charaachievementcounter_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharaTitleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='chara',
            name='partner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_partner_of', to='chara.charapartner'),
        ),
        migrations.CreateModel(
            name='CharaTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tltles', to='chara.chara')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chara.charatitletype')),
            ],
            options={
                'unique_together': {('chara', 'type')},
            },
        ),
        migrations.AddField(
            model_name='chara',
            name='title',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_title_of', to='chara.charatitle'),
        ),
        migrations.AddField(
            model_name='charaachievementtype',
            name='title_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chara.charatitletype'),
        ),
    ]
