# Generated by Django 4.0 on 2022-02-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0027_charatitletype_alter_chara_partner_charatitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charatitle',
            name='chara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='chara.chara'),
        ),
    ]
