# Generated by Django 4.0 on 2022-02-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0028_alter_charatitle_chara'),
    ]

    operations = [
        migrations.AddField(
            model_name='charaskillsetting',
            name='times_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
