# Generated by Django 4.0 on 2022-02-19 11:58

from django.db import migrations, models
import django.db.models.deletion


def create_chara_config(apps, schema_editor):
    Chara = apps.get_model('chara', 'Chara')
    CharaConfig = apps.get_model('chara', 'CharaConfig')
    for chara in Chara.objects.all():
        CharaConfig.objects.create(chara=chara)


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0029_charaskillsetting_times_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharaConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('background', models.CharField(blank=True, max_length=255)),
                ('chara', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='chara.chara')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_chara_config)
    ]
