# Generated by Django 4.0 on 2022-02-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0030_characonfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='characonfig',
            name='theme',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=10),
        ),
    ]
