# Generated by Django 4.0 on 2022-03-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0031_characonfig_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='charaskillsetting',
            name='probability',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
