# Generated by Django 4.0 on 2022-03-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0032_charaskillsetting_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='characonfig',
            name='default_autofight_status',
            field=models.BooleanField(default=False),
        ),
    ]
