# Generated by Django 4.0 on 2022-03-30 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def create_chara_custom_title(apps, schema_editor):
    Chara = apps.get_model('chara', 'Chara')
    CharaCustomTitle = apps.get_model('chara', 'CharaCustomTitle')
    for chara in Chara.objects.all():
        CharaCustomTitle.objects.create(chara=chara)


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0033_characonfig_default_autofight_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharaCustomTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('due_time', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('chara', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='custom_title', to='chara.chara')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_chara_custom_title)
    ]
