# Generated by Django 4.0 on 2022-04-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0034_characustomtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='charaachievementtype',
            name='need_announce',
            field=models.BooleanField(default=False),
        ),
    ]
