# Generated by Django 4.0 on 2022-04-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0035_charaachievementtype_need_announce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chara',
            old_name='member_point',
            new_name='member_point_paid',
        ),
    ]
