# Generated by Django 4.0 on 2022-04-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0037_chara_member_point_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='characonfig',
            name='use_image_background',
            field=models.BooleanField(default=True),
        ),
    ]
