# Generated by Django 3.0.6 on 2021-07-11 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chara', '0011_chara_avatar_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=10)),
                ('leader', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_of', to='chara.Chara')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamJoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_join_requests', to='chara.Chara')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_join_requests', to='team.Team')),
            ],
            options={
                'unique_together': {('team', 'chara')},
            },
        ),
    ]
