# Generated by Django 3.0.6 on 2021-07-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_battleresult_dungeon_dungeonfloor'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDungeonRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('passed_times', models.PositiveIntegerField(default=0)),
                ('current_floor', models.PositiveIntegerField(default=0)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_records', to='battle.Dungeon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_records', to='team.Team')),
            ],
            options={
                'unique_together': {('team', 'dungeon')},
            },
        ),
    ]
