# Generated by Django 3.2 on 2021-09-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teamdungeonrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdungeonrecord',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active'), ('ended', 'ended')], default='inactive', max_length=10),
        ),
    ]
