# Generated by Django 3.2 on 2021-10-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_teamdungeonrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdungeonrecord',
            name='start_floor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
