# Generated by Django 3.0.6 on 2021-06-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0003_remove_town_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
