# Generated by Django 3.0.6 on 2020-09-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('world', '0001_initial'),
        ('chara', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.ItemType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('price', models.IntegerField()),
                ('store_type', models.CharField(choices=[('weapon', 'weapon'), ('armor', 'armor'), ('jewelry', 'jewelry'), ('item', 'item')], max_length=10)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.ItemType')),
                ('location_element_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='world.ElementType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('price', models.BigIntegerField()),
                ('due_time', models.DateTimeField()),
                ('item_received', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_buyer_of', to='chara.Chara')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='item.Item')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_seller_of', to='chara.Chara')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('due_time', models.DateTimeField()),
                ('gold_received', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_buyer_of', to='chara.Chara')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.ItemType')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_seller_of', to='chara.Chara')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeOptionRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.IntegerField()),
                ('exchange_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='trade.ExchangeOption')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.ItemType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('reserve_price', models.BigIntegerField()),
                ('bid_price', models.BigIntegerField(null=True)),
                ('due_time', models.DateTimeField()),
                ('item_received', models.BooleanField(default=False)),
                ('gold_received', models.BooleanField(default=False)),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_bidder_of', to='chara.Chara')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='item.Item')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_seller_of', to='chara.Chara')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
