# Generated by Django 3.2 on 2021-08-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='deposit',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='deposit',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
