# Generated by Django 3.2 on 2021-10-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_equipment_is_locked'),
        ('trade', '0003_lottery_lotteryticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item'),
        ),
    ]
