# Generated by Django 3.2 on 2021-11-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0015_chara_luck_base'),
        ('item', '0006_equipment_is_locked'),
        ('trade', '0005_alter_sale_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('price', models.IntegerField()),
                ('message', models.CharField(blank=True, max_length=100)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_parcels', to='chara.chara')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_parcels', to='chara.chara')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
