# Generated by Django 3.2 on 2021-12-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeoption',
            name='store_type',
            field=models.CharField(choices=[('exchange', 'exchange'), ('cooking', 'cooking')], default='exchange', max_length=10),
            preserve_default=False,
        ),
    ]
