# Generated by Django 4.0 on 2022-01-16 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20211114_1205'),
        ('chara', '0022_alter_charapartner_unique_together_and_more'),
        ('npc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('friendliness_reward', models.IntegerField()),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.itemtype')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='npc.npc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NPCExchangeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('friendliness_cost', models.IntegerField()),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.itemtype')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_options', to='npc.npc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NPCCharaRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('friendliness', models.IntegerField(default=0)),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc_relations', to='chara.chara')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chara_relations', to='npc.npc')),
            ],
            options={
                'unique_together': {('npc', 'chara')},
            },
        ),
    ]
