# Generated by Django 4.0 on 2022-03-26 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('npc', '0005_npc_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='has_image',
        ),
        migrations.AddField(
            model_name='npc',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.image'),
        ),
    ]
