# Generated by Django 3.2 on 2021-12-12 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0007_auto_20211114_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.IntegerField(default=1)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farming_input_of', to='item.itemtype')),
                ('reward_item_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farming_reward_of', to='item.itemtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
