# Generated by Django 3.0.6 on 2021-05-27 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_country_item_limit'),
        ('world', '0002_auto_20200901_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='country.Country'),
        ),
    ]
