# Generated by Django 3.0.6 on 2021-05-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_location_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='chaos_score',
        ),
    ]
