# Generated by Django 3.2 on 2021-12-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_remove_location_chaos_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationBuffEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='locationbuff',
            name='value',
        ),
        migrations.RemoveField(
            model_name='locationbufftype',
            name='is_positive',
        ),
        migrations.AlterField(
            model_name='locationbuff',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffs', to='world.location'),
        ),
        migrations.AlterField(
            model_name='locationbufftype',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='locationbufftype',
            name='effect',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='world.locationbuffeffect'),
            preserve_default=False,
        ),
    ]
