# Generated by Django 3.2 on 2021-12-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_locationbufftype_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationbufftype',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
