# Generated by Django 4.0 on 2022-02-03 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0007_locationbufftype_description'),
        ('chara', '0022_alter_charapartner_unique_together_and_more'),
        ('job', '0001_initial'),
        ('ability', '0002_auto_20200901_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGCDungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('max_floor', models.IntegerField()),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chara.chara')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UGCDungeonFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('floor', models.IntegerField()),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='ugc.ugcdungeon')),
            ],
            options={
                'unique_together': {('dungeon', 'floor')},
            },
        ),
        migrations.CreateModel(
            name='UGCMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('hp', models.PositiveIntegerField()),
                ('mp', models.PositiveIntegerField()),
                ('abilities', models.ManyToManyField(to='ability.Ability')),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chara.chara')),
                ('element_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='world.elementtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UGCMonsterSkillSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('hp_percentage', models.PositiveSmallIntegerField()),
                ('mp_percentage', models.PositiveSmallIntegerField()),
                ('defender_hp_percentage', models.PositiveSmallIntegerField(default=100)),
                ('defender_mp_percentage', models.PositiveSmallIntegerField(default=100)),
                ('order', models.IntegerField()),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_settings', to='ugc.ugcmonster')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UGCDungeonFloorMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dungeon_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='ugc.ugcdungeonfloor')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.ugcmonster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UGCMonsterAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.IntegerField()),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ugc.ugcmonster')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='world.attributetype')),
            ],
            options={
                'unique_together': {('monster', 'type')},
            },
        ),
    ]
