# Generated by Django 4.0 on 2022-02-03 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chara', '0022_alter_charapartner_unique_together_and_more'),
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharaUGCDungeonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('active', 'active'), ('ended', 'ended')], default='inactive', max_length=10)),
                ('start_floor', models.PositiveIntegerField(default=0)),
                ('current_floor', models.PositiveIntegerField(default=0)),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chara.chara')),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.ugcdungeon')),
            ],
            options={
                'unique_together': {('chara', 'dungeon')},
            },
        ),
    ]
