# Generated by Django 4.0 on 2022-03-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_ugcmonsterskillsetting_times_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugcmonsterskillsetting',
            name='probability',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
