# Generated by Django 3.0.6 on 2020-09-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('ability', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alchemyoption',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.ItemType'),
        ),
        migrations.AddField(
            model_name='ability',
            name='attribute_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='world.AttributeType'),
        ),
        migrations.AddField(
            model_name='ability',
            name='prerequisite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ability.Ability'),
        ),
        migrations.AddField(
            model_name='ability',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ability.AbilityType'),
        ),
    ]
