# Generated by Django 3.0.6 on 2021-06-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='member_point',
        ),
    ]
