# Generated by Django 3.0.6 on 2020-09-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ability', '0002_auto_20200901_1442'),
        ('job', '0001_initial'),
        ('world', '0001_initial'),
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterskillsetting',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Skill'),
        ),
        migrations.AddField(
            model_name='monsterattribute',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='battle.Monster'),
        ),
        migrations.AddField(
            model_name='monsterattribute',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='world.AttributeType'),
        ),
        migrations.AddField(
            model_name='monster',
            name='abilities',
            field=models.ManyToManyField(to='ability.Ability'),
        ),
        migrations.AddField(
            model_name='monster',
            name='element_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='world.ElementType'),
        ),
        migrations.AddField(
            model_name='battlemapmonster',
            name='battle_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='battle.BattleMap'),
        ),
        migrations.AddField(
            model_name='battlemapmonster',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Monster'),
        ),
        migrations.AlterUniqueTogether(
            name='monsterattribute',
            unique_together={('monster', 'type')},
        ),
    ]
