# Generated by Django 3.0.6 on 2021-06-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_auto_20200901_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlemap',
            name='exp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='proficiency',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
