# Generated by Django 3.2 on 2021-09-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_equipment_is_locked'),
        ('battle', '0006_auto_20210918_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('divisor', models.IntegerField()),
                ('number', models.IntegerField(default=1)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='battle.dungeon')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.itemtypepoolgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
