# Generated by Django 3.2 on 2021-09-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0007_dungeonreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='gold_reward_per_floor',
            field=models.IntegerField(default=0),
        ),
    ]
