# Generated by Django 3.2 on 2021-09-19 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0008_dungeon_gold_reward_per_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dungeonfloor',
            name='monsters',
        ),
        migrations.CreateModel(
            name='DungeonFloorMonster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dungeon_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='battle.dungeonfloor')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle.monster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
