# Generated by Django 3.2 on 2021-09-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0009_auto_20210919_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterskillsetting',
            name='defender_hp_percentage',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='monsterskillsetting',
            name='defender_mp_percentage',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
