# Generated by Django 3.2 on 2021-09-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ability', '0002_auto_20200901_1442'),
        ('world', '0004_remove_location_chaos_score'),
        ('job', '0001_initial'),
        ('battle', '0010_auto_20210922_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldBoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=40)),
                ('hp_max', models.PositiveIntegerField()),
                ('hp', models.PositiveIntegerField()),
                ('mp_max', models.PositiveIntegerField()),
                ('mp', models.PositiveIntegerField()),
                ('abilities', models.ManyToManyField(to='ability.Ability')),
                ('element_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='world.elementtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldBossTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('base_attribute', models.IntegerField()),
                ('base_hp', models.IntegerField()),
                ('base_mp', models.IntegerField()),
                ('difficulty', models.FloatField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldBossSkillSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('hp_percentage', models.PositiveSmallIntegerField()),
                ('mp_percentage', models.PositiveSmallIntegerField()),
                ('defender_hp_percentage', models.PositiveSmallIntegerField(default=100)),
                ('defender_mp_percentage', models.PositiveSmallIntegerField(default=100)),
                ('order', models.IntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.skill')),
                ('world_boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_settings', to='battle.worldboss')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldBossNameBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AddField(
            model_name='worldboss',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle.worldbosstemplate'),
        ),
        migrations.CreateModel(
            name='WorldBossAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='world.attributetype')),
                ('world_boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='battle.worldboss')),
            ],
            options={
                'unique_together': {('world_boss', 'type')},
            },
        ),
    ]
