# Generated by Django 3.2 on 2021-09-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_remove_location_chaos_score'),
        ('battle', '0011_auto_20210928_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldboss',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='world.location'),
            preserve_default=False,
        ),
    ]
