# Generated by Django 3.2 on 2021-12-29 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_locationbufftype_description'),
        ('chara', '0019_charafarm'),
        ('battle', '0012_worldboss_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('occupied_at', models.DateTimeField(null=True)),
                ('occupier_win_count', models.IntegerField(default=0)),
                ('attribute_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='world.attributetype')),
                ('occupier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chara.chara')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
