# Generated by Django 4.0 on 2022-02-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0013_arena'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterskillsetting',
            name='times_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worldbossskillsetting',
            name='times_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
