# Generated by Django 4.0 on 2022-03-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0014_monsterskillsetting_times_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterskillsetting',
            name='probability',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='worldbossskillsetting',
            name='probability',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
