# Generated by Django 4.0 on 2022-04-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0016_battleeffecttype_battleeffect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleeffect',
            name='value',
            field=models.FloatField(),
        ),
    ]
