# Generated by Django 4.0 on 2022-02-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltype',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
