# Generated by Django 4.0 on 2022-06-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_adventureeventeffecttype_alter_adventurebattle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureevent',
            name='candidate_effects',
            field=models.ManyToManyField(to='adventure.AdventureEventEffect'),
        ),
        migrations.AddField(
            model_name='adventureevent',
            name='chooser',
            field=models.CharField(choices=[('random', 'random'), ('chara', 'chara')], default='random', max_length=10),
            preserve_default=False,
        ),
    ]
