# Generated by Django 4.0 on 2022-06-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_adventureevent_candidate_effects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='max_step',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adventurerecord',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='adventure.adventure'),
        ),
    ]
