# Generated by Django 4.0 on 2022-06-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_adventure_max_step_alter_adventurerecord_adventure'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurestep',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
